# Generated by Django 3.2.9 on 2022-04-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'data',
            },
        ),
    ]
